poppy-project/pypot

pypot/sensor/kinect/sensor.py

+ Changes json formated string to csv values
+ Change the name of the subscriber socket in case we add more sockets to receive RGB and depth informations

Changes the received format of kinect data

---

pypot/tools/herborist/herborist.ui

Signed-off-by: Philippe Coval <rzr@gna.org>

ui: Enhance display for small screens

---

pypot/vrep/child_script/inject_code.lua
pypot/vrep/child_script/timer.lua
pypot/vrep/io.py

Add a child script that blindly evaluates all lua string send to it as a string signal.
Waiting for @sebastien-forestier for testing it.

Lua code injection to the V-REP simulation

---

pypot/primitive/primitive.py
pypot/utils/stoppablethread.py

Most likely due to absolute import.
@show0k does this fix the problem ?

Fix circular import issue with python 3 

---

.travis.yml
ci/README.md
ci/after_success_release.sh
ci/before_install.sh
ci/flake8.config
ci/get_pypi_last_version.py
ci/install.sh
ci/run_examples.sh
ci/run_tests.sh
ci/update_documentation.sh

No true tests are made (we have to written them), but it can push dist files of linux and osx on Pypi and update the doc.
I tried to make V-REP works, but there is a communication issue (maybe the vm is too slow)

Add travis "tests"

---

pypot/dynamixel/controller.py

ping @show0k (first PR from [feuvert](http://www.feuvert.fr)...)

Fix unpack values at startup

---

.travis.yml
ci/before_install.sh
ci/install.sh
ci/run_tests.sh
pypot/dynamixel/__init__.py
pypot/dynamixel/controller.py
pypot/dynamixel/io/abstract_io.py
pypot/dynamixel/io/io.py
pypot/primitive/manager.py
pypot/server/snap.py
pypot/utils/stoppablethread.py
tests/test_primitive.py
tests/test_snap.py

WIP: This PR tries to fix #144 and #139 
I fix a tricky indentation issue that prevents the teardown of a primitive to be correctly synced before stopping it. It seems to have fixed the led issues with the Dance primitive for instance where green LEDs were staying on after the end of the dance.

Led control issue

---

pypot/server/snap.py

@Tibo42 I let you test the two new URLs:
* /ik/\<chain>/endeffector
* /ik/\<chain>/goto/\<x>/\<y>/\<z>/\<duration>

Add snap URL for ik.

---

conda.recipe/bld.bat
conda.recipe/build.sh
conda.recipe/meta.yaml
pypot/sensor/__init__.py
pypot/sensor/imagefeature/__init__.py
setup.py
tests/test_import.py

You can test it with `conda build conda.recipe/ --python=2.7 --python=3.3 --python=3.4 --python=3.5`.

Add a conda recipe

---

pypot/dynamixel/__init__.py

I think we have to make a bugfix release...

Fix uninported DxlError

---

pypot/dynamixel/io/abstract_io.py
pypot/dynamixel/io/io.py

Fixed a bug in AbstractDxlIO that thew an error due to missing attribute _DxlIO__controls
Added support for Punch register (0x30) for AX and RX series.

solved a bug for get_control_table and added punch register

---

pypot/robot/controller.py
pypot/utils/stoppablethread.py
tests/test_dummy.py

Original issue described by https://github.com/poppy-project/pypot/issues/166

Fix offset/orientation issue with DummyController.

---

pypot/server/snap.py

With find_host_ip('localhost') there, the `socket.gethostbyname_ex(host)[2]` couldn't give other result than 127.0.0.1, and there was a timeout error on `socket.connect(('8.8.8.8', 53))` if there is no internet connection...
So, I added an exception for the timeout and remove the `find_local_ip = lambda: find_host_ip('localhost')` which cannot give any results different than 127.0.0.1...

Fix find_local_ip

---

pypot/primitive/move.py

Add a plot method for a move.

---

pypot/sensor/__init__.py
pypot/sensor/contact/__init__.py
pypot/sensor/contact/contact.py

Please feel free to pythonify it.

add contact sensor

---

MANIFEST.in
ci/get_pypi_last_version.py
setup.py

It should fix the second issue of #196

Add markdown files to archive and fix encoding issue in Python 3+

---

pypot/creatures/__init__.py

Check done. No problem to use all the poppy-services with externe creatures roboticia-*

adding externe creature

---

.travis.yml
pypot/sensor/arduino/__init__.py
pypot/sensor/arduino/uno.py

Continuing on #206:
Cool contribution! Thanks @jjehl 
I've made some small modification to make pep8 happier and be less agressive in the try/catch. 
It would also be great to show an example of the Arduino side? Maybe in the documentation of uno.py? Or simply adding a link to a gist example? What do you say @jjehl ?

Jjehl Arduino sensor

---

pypot/sensor/arduino/__init__.py
pypot/sensor/arduino/uno.py

A simple reading of the serial port with an arduino connected by usb and sendind sensor's data. Testing with data frequence at 100 Hz and communication at 1 000 000 bauds.
Could be useful to connect a lot of variant sensors compatible with arduino.
Retrieve the data in json format.

arduino sensor

---

pypot/server/rest.py

@show0k can you review this please?

Fix start_move_recorder when motors is None

---

pypot/dynamixel/conversion.py

This PR is to address this issue: https://github.com/poppy-project/pypot/issues/226

Add XL-320 baud rate
